trigger:
- master
- develop
- features/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'jacksondr5'
    scannerMode: 'CLI'
    configMode: 'file'

- script: npm run build
  displayName: 'Build Project'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'